input_stream: "input_video"
input_stream:  "input_audio"
output_stream: "output_video"

node: {
  calculator: "face.face.FaceRecognizer"
  input_stream: "input_video"
  input_stream: "door_status"
  output_stream: "output_face"
  output_stream: "face_recognized"
}

node: {
  calculator: "VoskVoiceToTextCalculator"
  input_stream: "input_audio"
  input_stream: "face_recognized"
  output_stream: "voice_to_text"
  output_stream: "voice_to_word"
}

node: {
  calculator: "ShowStatusImageFromFiles"
  input_stream: "voice_to_text"
  input_stream: "face_recognized"
  output_stream: "door_light"
  output_stream: "door_status"
  map_node_options: {
    stringOptions: { key:"onImage"; value:"images/on.png" }
    stringOptions: { key:"onWord";  value:"open" }
    stringOptions: { key:"offImage"; value:"images/off.png" }
    stringOptions: { key:"errImage"; value:"images/err.png" }
    doubleOptions: { key:"statusOnTime"; value:4.0 }
  }
}


node: {
  calculator: "PlaySound"
  input_stream: "voice_to_text"
  input_stream: "face_recognized"
  map_node_options: {
    stringOptions: { key:"onOpenMorn"; value:"sounds/gm_welcome.wav" }
    stringOptions: { key:"onOpenEven"; value:"sounds/ge_welcome.wav" }
    stringOptions: { key:"sorry"; value:"sounds/sorry_no_access.wav" }
    stringOptions: { key:"audio"; value:"name:Jabra" }
  }
}

node: {
    calculator: "ShowImage"
    input_stream: "door_light"
    map_node_options: {
        stringOptions: { key:"windowTitle"; value:"Door Status" }
    }
}

node: {
    calculator: "ShowImage"
    input_stream: "output_face"
    map_node_options: {
        stringOptions: { key:"windowTitle"; value:"Face Status" }
    }
}


node: {
  calculator: "ConsumerNode"
  input_stream: "voice_to_word"
  input_stream: "output_face"
}
