input_stream: "input_video"

node: {
  calculator: "HandDetector2"
  input_stream: "input_video"
  input_stream: "yolo_detections"
  input_stream: "door_status"
  output_stream: "hand_detections"
}

node: {
  calculator: "HandThumbDetector"
  input_stream: "hand_detections"
  output_stream: "thumb_detections"
}

node: {
  calculator: "ShowStatusImageFromFiles"
  input_stream: "thumb_detections"
  input_stream: "yolo_detections"
  output_stream: "door_light"
  output_stream: "door_status"
  map_node_options: {
    stringOptions: { key:"windowTitle"; value:"Thumb Status" }
    stringOptions: { key:"onImage"; value:"images/on.png" }
    stringOptions: { key:"offImage"; value:"images/off.png" }
    stringOptions: { key:"errImage"; value:"images/err.png" }
    stringOptions: { key:"onWord";  value:"Thumb up" }
    stringOptions: { key:"errWord";  value:"No Mask" }
    doubleOptions: { key:"statusOnTime"; value: 4.5 }
    }
}

node: {
  calculator: "TRTYoloDetector"
  input_stream: "input_video"
  input_stream: "door_status"
  output_stream: "yolo_detections"
}

node: {
  calculator: "PlaySound"
  input_stream: "thumb_detections"
  input_stream: "yolo_detections"
  map_node_options: {
    stringOptions: { key:"onOpenMorn"; value:"Good morning, welcome" }
    stringOptions: { key:"onOpenEven"; value:"Good morning, welcome" }
    stringOptions: { key:"sorry"; value:"Please wear a mask" }
    stringOptions: { key:"errWord"; value:"No Mask" }
    stringOptions: { key:"onWord";  value:"Thumb up" }
    stringOptions: { key:"audio"; value:"name:Jabra" }
  }
}

node: {
    calculator: "ShowImage"
    input_stream: "door_light"
    map_node_options: {
        stringOptions: { key:"windowTitle"; value:"Door Status" }
    }
}


node: {
    calculator: "ShowImage"
    input_stream: "input_video"
    map_node_options: {
        stringOptions: { key:"windowTitle"; value:"Input" }
    }
}



