input_stream: "input_audio"

node: {
  calculator: "TriggerWordDetector"
  input_stream: "input_audio"
  output_stream: "trigger_word"
}

node: {
  calculator: "PlayAlarm"
  input_stream: "trigger_word"
  input_stream: "Alarm"
}

node: {
    calculator: "SwitchButton"
    input_stream: "trigger_word"
    output_stream: "Alarm"
}
