# MediaPipe graph that performs YoloV3 in CV2 detection on a live video stream.
# Images coming into and out of the graph.

input_stream: "input_video"
output_stream: "output_video"

node: {
  calculator: "HandDetector"
  input_stream: "input_video"
  output_stream: "hand_detector_img"
  output_stream: "hand_detections"
}

node: {
  calculator: "HandThumbDetector"
  input_stream: "hand_detections"
  output_stream: "thumb_detections"
}

# Applies a box and label annotator to the image
node: {
  calculator: "DrawHandDetections"
  input_stream: "input_video"
  input_stream: "hand_detections"
  output_stream: "output_video"
}


node: {
  calculator: "ConsumerNode"
  input_stream: "hand_detector_img"
  input_stream: "thumb_detections"
}

